project_id = "qrgelocijmwnxcckxbdg"

[functions.create-mercadopago-preference]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false