project_id = "qrgelocijmwnxcckxbdg"

[functions.create-mercadopago-preference]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.meta-conversions]
verify_jwt = false

[functions.booking-calendar-callback]
verify_jwt = false

[functions.clever-action]
verify_jwt = false

[functions.enqueue-booking-calendar]
verify_jwt = false