// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhhtigrrenqkagtlwrju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoaHRpZ3JyZW5xa2FndGx3cmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDc5NTYsImV4cCI6MjA2NzA4Mzk1Nn0.ATd8YI-fUF5T6u4-J1WjsNJIQltI6cC41KXXh2Rlt6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});