// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://qrgelocijmwnxcckxbdg.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZ2Vsb2Npam13bnhjY2t4YmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDI0MjksImV4cCI6MjA3MzM3ODQyOX0.0q_3bb8bKR8VVZZAK_hYvhvLSTaU1ioQzmO5fKALjbI';

// Mostrar información de diagnóstico en desarrollo
if (import.meta.env.DEV) {
  console.log('🔧 Supabase Diagnostics:', {
    url: SUPABASE_URL,
    keyLength: SUPABASE_PUBLISHABLE_KEY.length,
    credentialsValid: true,
    mode: 'online',
    projectRef: 'qrgelocijmwnxcckxbdg'
  });
  console.log('✅ SUPABASE: Credenciales válidas, modo online activado');
  console.log('✅ SUPABASE: Proyecto: qrgelocijmwnxcckxbdg');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false, // Deshabilitamos para evitar refresh automático
    autoRefreshToken: false, // Deshabilitamos refresh automático
    detectSessionInUrl: false,
  },
  global: {
    headers: {
      'X-Client-Info': 'punto-legal-app'
    }
  }
});

// Función para verificar conectividad
export const checkSupabaseConnection = async (): Promise<boolean> => {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3000); // 3 segundos timeout
    
    const response = await fetch(`${SUPABASE_URL}/rest/v1/`, {
      method: 'HEAD',
      signal: controller.signal,
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY
      }
    });
    
    clearTimeout(timeoutId);
    return response.ok;
  } catch (error) {
    console.warn('Supabase no disponible, usando modo offline:', error);
    return false;
  }
};